FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the app code
COPY app /app/app

# The command will be overridden by docker-compose
CMD ["python", "app/producers/listings_producer.py"]
